//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
struct Particle {
	vec3  position;
	float temperature;
	vec3  velocity;
	float sea_surface_temperature;
};

struct Texture {
	uint start;
	uint width;
	uint height;
	uint format;
};

struct Bvh {
	vec3 p_min;
	uint particle_start;
	vec3 p_max;
	uint particle_end;
	ivec4 pointers_a;
	ivec4 pointers_b;
};
// INTERNAL ---------------------------------------------------------------------------------------
// ------------------------------------------------------------------------------------------------

struct Ray {
	vec3  origin;
	vec3  direction;
};
struct StackNode {
	int index;
	float tmin;
	float tmax;
};
// DEFINITIONS ------------------------------------------------------------------------------------
// ------------------------------------------------------------------------------------------------
#define TWO_PI   6.28318530718
#define PI       3.14159265359
#define HALF_PI  1.57079632679
#define INV_PI   0.31830988618
#define DEG_RAD  0.01745329252
#define RAD_DEG  0.01745329252

#define MAX_DIST 1000.0
#define EPSILON  0.00001

#define MAX_UINT 4294967295