//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
struct Particle {
	vec3  position;
	float temperature;
	vec4  velocity;
};

struct Cell {
	float density;
	float humidity;
	float pressure;
	float temperature;

	vec3 pmin;
	uint a;
	vec3 pmax;
	uint b;
};

struct Octree {
	uvec4 pointers_a;
	uvec4 pointers_b;
	vec3 pmin;
	uint leaf;
	vec3 pmax;
	uint pad;
};

// INTERNAL ---------------------------------------------------------------------------------------
// ------------------------------------------------------------------------------------------------
struct AABB {
	vec3 pmin;
	vec3 pmax;
};

struct Ray {
	vec3  origin;
	vec3  direction;
};
// DEFINITIONS ------------------------------------------------------------------------------------
// ------------------------------------------------------------------------------------------------
#define TWO_PI   6.28318530718
#define PI       3.14159265359
#define HALF_PI  1.57079632679
#define INV_PI   0.31830988618
#define DEG_RAD  0.01745329252
#define RAD_DEG  0.01745329252

#define MAX_DIST 1000.0
#define EPSILON  0.00001

#define MAX_UINT 4294967295