//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
struct Particle {
	vec3  position;
	float temperature;
	vec3  velocity;
	float sea_surface_temperature;
};

struct Texture {
	uint start;
	uint width;
	uint height;
	uint format;
	// 16
};

struct Bvh {
	vec3 p_min;
	uint particle_count; // If == 0, pointer leads to other Bvh Node, else leads to End Index
	vec3 p_max;
	uint pointer_particle;
	uint pointer_a;
	uint pointer_b;
	uvec2 padding;
	// 48
};
// INTERNAL ---------------------------------------------------------------------------------------
// ------------------------------------------------------------------------------------------------

struct Ray {
	vec3  origin;
	vec3  direction;
};
// DEFINITIONS ------------------------------------------------------------------------------------
// ------------------------------------------------------------------------------------------------
#define TWO_PI   6.28318530718
#define PI       3.14159265359
#define HALF_PI  1.57079632679
#define INV_PI   0.31830988618
#define DEG_RAD  0.01745329252
#define RAD_DEG  0.01745329252

#define MAX_DIST 1000.0
#define EPSILON  0.00001

#define MAX_UINT 4294967295